[mgr]
show_hidden = true

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
image = [
	{ run = 'imv "$@"', orphan = true, for = "unix" },
]
pdf = [
	{ run = 'zathura "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]

[open]
rules = [
	{ mime = "image/*", use = "image" },
	{ mime = "application/pdf", use = "pdf" },
	{ mime = "video/*", use = "play" },
	{ mime = "audio/*", use = "play" },
	{ mime = "text/*", use = "edit" },
	{ mime = "application/json", use = "edit" },
	{ mime = "application/javascript", use = "edit" },
	{ mime = "application/x-shellscript", use = "edit" },
	{ mime = "*", use = "edit" },
]
