theme = "nord_transparent"

[editor]
line-number = "relative"
bufferline = "multiple"
gutters = ["line-numbers", "spacer", "diff"]
scrolloff = 10
color-modes = true
true-color = true
undercurl = true
soft-wrap.enable = true
rulers = [120]
clipboard-provider = "wayland"
end-of-line-diagnostics = "hint"
file-picker.hidden = false
path-completion = true
auto-format = true
trim-trailing-whitespace = false
trim-final-newlines = false

[editor.indent-guides]
render = true
trim-trailing-whitespace = true
character = "▏"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = [
  "mode",
  "file-name",
  "version-control",
  "spinner",
  "read-only-indicator",
  "file-modification-indicator",
]
right = ["diagnostics", "selections", "position", "file-type"]
separator = '-'

[editor.lsp]
goto-reference-include-declaration = false
display-inlay-hints = false
display-progress-messages = true

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = " "
tabpad = "␣"

[editor.whitespace]
render = "all"

[keys.normal]
H = ":buffer-previous"
L = ":buffer-next"
G = "goto_file_end"
V = ["extend_line_below", "select_mode"]
y = "yank_to_clipboard"
Y = "yank"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[keys.normal.space]
q = ":quit"
e = [
  ':sh rm -f /tmp/yazi-path',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/yazi-path',
  ":open %sh{cat /tmp/yazi-path}",
  ":redraw",
]

[keys.normal.space.b]
"d" = ":buffer-close"

[keys.insert]
C-h = ["jump_view_left", "insert_mode"]
C-l = ["jump_view_right", "insert_mode"]
