# [[language]]
# name = "bash"
# formatter = { command = "shfmt" }
# auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'prettierd', args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'biome', args = ["--parser", "javascript"] }
auto-format = true
language-servers = [ "typescript-language-server" ]

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'biome', args = ["--parser", "typescript"] }
auto-format = true
language-servers = [ "typescript-language-server" ]

[[language]]
name = "tsx"
formatter = { command = 'biome', args = ["--parser", "typescript"] }
auto-format = true
language-servers = [ "typescript-language-server" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "go"
language-servers = [ "gopls" ]
formatter = { command = 'gofmt' }
auto-format = true

[[language]]
name = "zig"
language-servers = [ "zls" ]
formatter = { command = '' }
auto-format = true


[[language]]
name = "json"
file-types = ["json", "jsonc"]
formatter = { command = 'prettierd', args = ["prettierd", "--parser", "json"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettierd', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'biome', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = 'prettierd', args = ["--parser", "yaml"] }
auto-format = true

# [[language]]
# name = "toml"
# formatter = { command = "taplo", args = ["format", "-"] }
# auto-format = true

[language-server.taplo.config]
root_dir = [".git", "*.toml"]
