id = "nord"
name = "Nord Themes"
version = "0.1.2"
schema_version = 1
description = "Nord color schemes for Zed. Includes light and dark variants."
repository = "https://github.com/mikasius/zed-nord-theme"
authors = ["Sergei Metlenkin <s.metlenkin@gmail.com>"]
themes = ["themes/nord.json"]
icon_themes = []
languages = []
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
